'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3615
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.3615.
'
Namespace WebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="zservicios_fe_v2", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class zservicios_fe_v2
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CargaDteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.IntercambioRespuestasSII.My.MySettings.Default.IntercambioRespuestasSII_WebReference_zservicios_fe_v2
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CargaDteCompleted As CargaDteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function CargaDte(<System.Xml.Serialization.XmlElementAttribute("CargaDte", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal CargaDte1 As CargaDte) As <System.Xml.Serialization.XmlElementAttribute("CargaDteResponse", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> CargaDteResponse
            Dim results() As Object = Me.Invoke("CargaDte", New Object() {CargaDte1})
            Return CType(results(0),CargaDteResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CargaDteAsync(ByVal CargaDte1 As CargaDte)
            Me.CargaDteAsync(CargaDte1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CargaDteAsync(ByVal CargaDte1 As CargaDte, ByVal userState As Object)
            If (Me.CargaDteOperationCompleted Is Nothing) Then
                Me.CargaDteOperationCompleted = AddressOf Me.OnCargaDteOperationCompleted
            End If
            Me.InvokeAsync("CargaDte", New Object() {CargaDte1}, Me.CargaDteOperationCompleted, userState)
        End Sub
        
        Private Sub OnCargaDteOperationCompleted(ByVal arg As Object)
            If (Not (Me.CargaDteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CargaDteCompleted(Me, New CargaDteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class CargaDte
        
        Private cdgintrecepField As String
        
        Private cdgtrasladoField As String
        
        Private cdgvendedorField As String
        
        Private ciudadorigenField As String
        
        Private ciudadrecepField As String
        
        Private cmnaorigenField As String
        
        Private cmnarecepField As String
        
        Private correoemisorField As String
        
        Private correorecepField As String
        
        Private detalleField() As ZfeDetalle
        
        Private dirorigenField As String
        
        Private dirrecepField As String
        
        Private dscrcgglobalField() As ZfeDscrcgglobal
        
        Private fchemisField As String
        
        Private fchvencField As String
        
        Private firmaField As String
        
        Private fmapagoField As String
        
        Private folioField As String
        
        Private giroemisField As String
        
        Private girorecepField As String
        
        Private imptoretenField() As ZfeImpuestos
        
        Private indtrasladoField As String
        
        Private ivaField As String
        
        Private ivanoretField As String
        
        Private mntexeField As String
        
        Private mntnetoField As String
        
        Private mnttotalField As String
        
        Private montonfField As String
        
        Private montoperiodoField As String
        
        Private referenciaField() As ZfeReferencia
        
        Private rutemisorField As String
        
        Private rutrecepField As String
        
        Private rznsocField As String
        
        Private rznsocrecepField As String
        
        Private saldoanteriorField As String
        
        Private tasaivaField As String
        
        Private tipodteField As String
        
        Private tpomonedaField As String
        
        Private valcomexeField As String
        
        Private valcomivaField As String
        
        Private valcomnetoField As String
        
        Private vlrpagarField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cdgintrecep() As String
            Get
                Return Me.cdgintrecepField
            End Get
            Set
                Me.cdgintrecepField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cdgtraslado() As String
            Get
                Return Me.cdgtrasladoField
            End Get
            Set
                Me.cdgtrasladoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cdgvendedor() As String
            Get
                Return Me.cdgvendedorField
            End Get
            Set
                Me.cdgvendedorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ciudadorigen() As String
            Get
                Return Me.ciudadorigenField
            End Get
            Set
                Me.ciudadorigenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ciudadrecep() As String
            Get
                Return Me.ciudadrecepField
            End Get
            Set
                Me.ciudadrecepField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cmnaorigen() As String
            Get
                Return Me.cmnaorigenField
            End Get
            Set
                Me.cmnaorigenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Cmnarecep() As String
            Get
                Return Me.cmnarecepField
            End Get
            Set
                Me.cmnarecepField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Correoemisor() As String
            Get
                Return Me.correoemisorField
            End Get
            Set
                Me.correoemisorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Correorecep() As String
            Get
                Return Me.correorecepField
            End Get
            Set
                Me.correorecepField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Detalle() As ZfeDetalle()
            Get
                Return Me.detalleField
            End Get
            Set
                Me.detalleField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dirorigen() As String
            Get
                Return Me.dirorigenField
            End Get
            Set
                Me.dirorigenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dirrecep() As String
            Get
                Return Me.dirrecepField
            End Get
            Set
                Me.dirrecepField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Dscrcgglobal() As ZfeDscrcgglobal()
            Get
                Return Me.dscrcgglobalField
            End Get
            Set
                Me.dscrcgglobalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fchemis() As String
            Get
                Return Me.fchemisField
            End Get
            Set
                Me.fchemisField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fchvenc() As String
            Get
                Return Me.fchvencField
            End Get
            Set
                Me.fchvencField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Firma() As String
            Get
                Return Me.firmaField
            End Get
            Set
                Me.firmaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fmapago() As String
            Get
                Return Me.fmapagoField
            End Get
            Set
                Me.fmapagoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Folio() As String
            Get
                Return Me.folioField
            End Get
            Set
                Me.folioField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Giroemis() As String
            Get
                Return Me.giroemisField
            End Get
            Set
                Me.giroemisField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Girorecep() As String
            Get
                Return Me.girorecepField
            End Get
            Set
                Me.girorecepField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Imptoreten() As ZfeImpuestos()
            Get
                Return Me.imptoretenField
            End Get
            Set
                Me.imptoretenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Indtraslado() As String
            Get
                Return Me.indtrasladoField
            End Get
            Set
                Me.indtrasladoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Iva() As String
            Get
                Return Me.ivaField
            End Get
            Set
                Me.ivaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Ivanoret() As String
            Get
                Return Me.ivanoretField
            End Get
            Set
                Me.ivanoretField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mntexe() As String
            Get
                Return Me.mntexeField
            End Get
            Set
                Me.mntexeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mntneto() As String
            Get
                Return Me.mntnetoField
            End Get
            Set
                Me.mntnetoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Mnttotal() As String
            Get
                Return Me.mnttotalField
            End Get
            Set
                Me.mnttotalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Montonf() As String
            Get
                Return Me.montonfField
            End Get
            Set
                Me.montonfField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Montoperiodo() As String
            Get
                Return Me.montoperiodoField
            End Get
            Set
                Me.montoperiodoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Referencia() As ZfeReferencia()
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rutemisor() As String
            Get
                Return Me.rutemisorField
            End Get
            Set
                Me.rutemisorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rutrecep() As String
            Get
                Return Me.rutrecepField
            End Get
            Set
                Me.rutrecepField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rznsoc() As String
            Get
                Return Me.rznsocField
            End Get
            Set
                Me.rznsocField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Rznsocrecep() As String
            Get
                Return Me.rznsocrecepField
            End Get
            Set
                Me.rznsocrecepField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Saldoanterior() As String
            Get
                Return Me.saldoanteriorField
            End Get
            Set
                Me.saldoanteriorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tasaiva() As String
            Get
                Return Me.tasaivaField
            End Get
            Set
                Me.tasaivaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tipodte() As String
            Get
                Return Me.tipodteField
            End Get
            Set
                Me.tipodteField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tpomoneda() As String
            Get
                Return Me.tpomonedaField
            End Get
            Set
                Me.tpomonedaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Valcomexe() As String
            Get
                Return Me.valcomexeField
            End Get
            Set
                Me.valcomexeField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Valcomiva() As String
            Get
                Return Me.valcomivaField
            End Get
            Set
                Me.valcomivaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Valcomneto() As String
            Get
                Return Me.valcomnetoField
            End Get
            Set
                Me.valcomnetoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vlrpagar() As String
            Get
                Return Me.vlrpagarField
            End Get
            Set
                Me.vlrpagarField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZfeDetalle
        
        Private nrolindetField As String
        
        Private tpocodigoField As String
        
        Private vlrcodigoField As String
        
        Private nmbitemField As String
        
        Private dscitemField As String
        
        Private qtyitemField As String
        
        Private unmditemField As String
        
        Private prcitemField As String
        
        Private montoitemField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nrolindet() As String
            Get
                Return Me.nrolindetField
            End Get
            Set
                Me.nrolindetField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tpocodigo() As String
            Get
                Return Me.tpocodigoField
            End Get
            Set
                Me.tpocodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Vlrcodigo() As String
            Get
                Return Me.vlrcodigoField
            End Get
            Set
                Me.vlrcodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nmbitem() As String
            Get
                Return Me.nmbitemField
            End Get
            Set
                Me.nmbitemField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Dscitem() As String
            Get
                Return Me.dscitemField
            End Get
            Set
                Me.dscitemField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Qtyitem() As String
            Get
                Return Me.qtyitemField
            End Get
            Set
                Me.qtyitemField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Unmditem() As String
            Get
                Return Me.unmditemField
            End Get
            Set
                Me.unmditemField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Prcitem() As String
            Get
                Return Me.prcitemField
            End Get
            Set
                Me.prcitemField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Montoitem() As String
            Get
                Return Me.montoitemField
            End Get
            Set
                Me.montoitemField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZfeReferencia
        
        Private nrolinrefField As String
        
        Private tpodocrefField As String
        
        Private indglobalField As String
        
        Private foliorefField As String
        
        Private fchrefField As String
        
        Private codrefField As String
        
        Private razonrefField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nrolinref() As String
            Get
                Return Me.nrolinrefField
            End Get
            Set
                Me.nrolinrefField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tpodocref() As String
            Get
                Return Me.tpodocrefField
            End Get
            Set
                Me.tpodocrefField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Indglobal() As String
            Get
                Return Me.indglobalField
            End Get
            Set
                Me.indglobalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Folioref() As String
            Get
                Return Me.foliorefField
            End Get
            Set
                Me.foliorefField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Fchref() As String
            Get
                Return Me.fchrefField
            End Get
            Set
                Me.fchrefField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codref() As String
            Get
                Return Me.codrefField
            End Get
            Set
                Me.codrefField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Razonref() As String
            Get
                Return Me.razonrefField
            End Get
            Set
                Me.razonrefField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZfeImpuestos
        
        Private tipoimpField As String
        
        Private tasaimpField As String
        
        Private montoimpField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tipoimp() As String
            Get
                Return Me.tipoimpField
            End Get
            Set
                Me.tipoimpField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tasaimp() As String
            Get
                Return Me.tasaimpField
            End Get
            Set
                Me.tasaimpField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Montoimp() As String
            Get
                Return Me.montoimpField
            End Get
            Set
                Me.montoimpField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZfeDscrcgglobal
        
        Private nrolindrField As String
        
        Private tpomovField As String
        
        Private glosadrField As String
        
        Private tpovalorField As String
        
        Private valordrField As String
        
        Private valordrotrmndaField As String
        
        Private indexedrField As String
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Nrolindr() As String
            Get
                Return Me.nrolindrField
            End Get
            Set
                Me.nrolindrField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tpomov() As String
            Get
                Return Me.tpomovField
            End Get
            Set
                Me.tpomovField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Glosadr() As String
            Get
                Return Me.glosadrField
            End Get
            Set
                Me.glosadrField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Tpovalor() As String
            Get
                Return Me.tpovalorField
            End Get
            Set
                Me.tpovalorField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Valordr() As String
            Get
                Return Me.valordrField
            End Get
            Set
                Me.valordrField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Valordrotrmnda() As String
            Get
                Return Me.valordrotrmndaField
            End Get
            Set
                Me.valordrotrmndaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Indexedr() As String
            Get
                Return Me.indexedrField
            End Get
            Set
                Me.indexedrField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class CargaDteResponse
        
        Private codigoretornoField As String
        
        Private descripcioncodigoField As String
        
        Private detalleField() As ZfeDetalle
        
        Private dscrcgglobalField() As ZfeDscrcgglobal
        
        Private imptoretenField() As ZfeImpuestos
        
        Private referenciaField() As ZfeReferencia
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Codigoretorno() As String
            Get
                Return Me.codigoretornoField
            End Get
            Set
                Me.codigoretornoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Descripcioncodigo() As String
            Get
                Return Me.descripcioncodigoField
            End Get
            Set
                Me.descripcioncodigoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Detalle() As ZfeDetalle()
            Get
                Return Me.detalleField
            End Get
            Set
                Me.detalleField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Dscrcgglobal() As ZfeDscrcgglobal()
            Get
                Return Me.dscrcgglobalField
            End Get
            Set
                Me.dscrcgglobalField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Imptoreten() As ZfeImpuestos()
            Get
                Return Me.imptoretenField
            End Get
            Set
                Me.imptoretenField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property Referencia() As ZfeReferencia()
            Get
                Return Me.referenciaField
            End Get
            Set
                Me.referenciaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub CargaDteCompletedEventHandler(ByVal sender As Object, ByVal e As CargaDteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CargaDteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CargaDteResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CargaDteResponse)
            End Get
        End Property
    End Class
End Namespace
