'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/CrSeed.jws")>  _
        Public Property RespuestasSII_cl_sii_semilla_CrSeedService() As String
            Get
                Return CType(Me("RespuestasSII_cl_sii_semilla_CrSeedService"),String)
            End Get
            Set
                Me("RespuestasSII_cl_sii_semilla_CrSeedService") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/GetTokenFromSeed.jws")>  _
        Public Property RespuestasSII_cl_sii_token_GetTokenFromSeedService() As String
            Get
                Return CType(Me("RespuestasSII_cl_sii_token_GetTokenFromSeedService"),String)
            End Get
            Set
                Me("RespuestasSII_cl_sii_token_GetTokenFromSeedService") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/QueryEstDte.jws")>  _
        Public Property RespuestasSII_cl_sii_queryEstDte_QueryEstDteService() As String
            Get
                Return CType(Me("RespuestasSII_cl_sii_queryEstDte_QueryEstDteService"),String)
            End Get
            Set
                Me("RespuestasSII_cl_sii_queryEstDte_QueryEstDteService") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.0.50:3128/")>  _
        Public Property ProxyServer() As String
            Get
                Return CType(Me("ProxyServer"),String)
            End Get
            Set
                Me("ProxyServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property maximoIntentos() As String
            Get
                Return CType(Me("maximoIntentos"),String)
            End Get
            Set
                Me("maximoIntentos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property VidaSemillaMil() As String
            Get
                Return CType(Me("VidaSemillaMil"),String)
            End Get
            Set
                Me("VidaSemillaMil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DTE Recibido")>  _
        Public Property DteEstOK() As String
            Get
                Return CType(Me("DteEstOK"),String)
            End Get
            Set
                Me("DteEstOK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ws_fe")>  _
        Public Property WS_BCI_USER() As String
            Get
                Return CType(Me("WS_BCI_USER"),String)
            End Get
            Set
                Me("WS_BCI_USER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INICIO17")>  _
        Public Property WS_BCI_PASS() As String
            Get
                Return CType(Me("WS_BCI_PASS"),String)
            End Get
            Set
                Me("WS_BCI_PASS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("caranguiz")>  _
        Public Property ProxyUser() As String
            Get
                Return CType(Me("ProxyUser"),String)
            End Get
            Set
                Me("ProxyUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("caz1460")>  _
        Public Property ProxyPass() As String
            Get
                Return CType(Me("ProxyPass"),String)
            End Get
            Set
                Me("ProxyPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N")>  _
        Public Property Proxy_SI_NO() As String
            Get
                Return CType(Me("Proxy_SI_NO"),String)
            End Get
            Set
                Me("Proxy_SI_NO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("S")>  _
        Public Property Ws_BCI_Carga() As String
            Get
                Return CType(Me("Ws_BCI_Carga"),String)
            End Get
            Set
                Me("Ws_BCI_Carga") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://161.131.184.101:8000/sap/bc/srt/rfc/sap/zservicios_fe_v2/100/zservicios_fe"& _ 
            "_v2/zservicios_fe_v2")>  _
        Public ReadOnly Property IntercambioRespuestasSII_WebReference_zservicios_fe_v1() As String
            Get
                Return CType(Me("IntercambioRespuestasSII_WebReference_zservicios_fe_v1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("97006000-6")>  _
        Public Property RUT_APLICACION() As String
            Get
                Return CType(Me("RUT_APLICACION"),String)
            End Get
            Set
                Me("RUT_APLICACION") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("S")>  _
        Public Property OMITE_VAL_SII() As String
            Get
                Return CType(Me("OMITE_VAL_SII"),String)
            End Get
            Set
                Me("OMITE_VAL_SII") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\INTERCAMBIO_BCI\PROCESO2\Valida_SII")>  _
        Public Property VALIDA_EN_SII() As String
            Get
                Return CType(Me("VALIDA_EN_SII"),String)
            End Get
            Set
                Me("VALIDA_EN_SII") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.office365.com")>  _
        Public Property MAIL_HOST() As String
            Get
                Return CType(Me("MAIL_HOST"),String)
            End Get
            Set
                Me("MAIL_HOST") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("intercambiobci@jordan.cl")>  _
        Public Property MAIL_FROM() As String
            Get
                Return CType(Me("MAIL_FROM"),String)
            End Get
            Set
                Me("MAIL_FROM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("intercambiobci@jordan.cl")>  _
        Public Property MAIL_USER() As String
            Get
                Return CType(Me("MAIL_USER"),String)
            End Get
            Set
                Me("MAIL_USER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dte2007.")>  _
        Public Property MAIL_PASS() As String
            Get
                Return CType(Me("MAIL_PASS"),String)
            End Get
            Set
                Me("MAIL_PASS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property MAIL_PORT() As String
            Get
                Return CType(Me("MAIL_PORT"),String)
            End Get
            Set
                Me("MAIL_PORT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public Property MAIL_SSL() As String
            Get
                Return CType(Me("MAIL_SSL"),String)
            End Get
            Set
                Me("MAIL_SSL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CLIENTES\BCI\CERTIFICADO\certificado_digital_firmante_efactura.p12")>  _
        Public Property CertPath() As String
            Get
                Return CType(Me("CertPath"),String)
            End Get
            Set
                Me("CertPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bcicacho")>  _
        Public Property CertPass() As String
            Get
                Return CType(Me("CertPass"),String)
            End Get
            Set
                Me("CertPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\INTERCAMBIO_BCI\Proceso2\XMLS")>  _
        Public Property DtePathDteDescargados() As String
            Get
                Return CType(Me("DtePathDteDescargados"),String)
            End Get
            Set
                Me("DtePathDteDescargados") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\INTERCAMBIO_BCI\Proceso2\PROCESADOS")>  _
        Public Property DtePathProcOK() As String
            Get
                Return CType(Me("DtePathProcOK"),String)
            End Get
            Set
                Me("DtePathProcOK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\INTERCAMBIO_BCI\Proceso2\RECHAZADOS")>  _
        Public Property DtePathProcNOK() As String
            Get
                Return CType(Me("DtePathProcNOK"),String)
            End Get
            Set
                Me("DtePathProcNOK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\INTERCAMBIO_BCI\Proceso2\LOG")>  _
        Public Property DtePathLogEnvio() As String
            Get
                Return CType(Me("DtePathLogEnvio"),String)
            End Get
            Set
                Me("DtePathLogEnvio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\INTERCAMBIO_BCI\Proceso2\PENDIENTES")>  _
        Public Property DtePathDtePendientes() As String
            Get
                Return CType(Me("DtePathDtePendientes"),String)
            End Get
            Set
                Me("DtePathDtePendientes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("S")>  _
        Public Property OMITIR_GUIA() As String
            Get
                Return CType(Me("OMITIR_GUIA"),String)
            End Get
            Set
                Me("OMITIR_GUIA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\INTERCAMBIO_BCI\PROCESO2\TMP_RETENCION")>  _
        Public Property RUTA_TMP_RET_IVA() As String
            Get
                Return CType(Me("RUTA_TMP_RET_IVA"),String)
            End Get
            Set
                Me("RUTA_TMP_RET_IVA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("S")>  _
        Public Property RET_IVA_HABILITA_RZO_COMERCIAL() As String
            Get
                Return CType(Me("RET_IVA_HABILITA_RZO_COMERCIAL"),String)
            End Get
            Set
                Me("RET_IVA_HABILITA_RZO_COMERCIAL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N")>  _
        Public Property RET_IVA_HABILITA_RZO_SII() As String
            Get
                Return CType(Me("RET_IVA_HABILITA_RZO_SII"),String)
            End Get
            Set
                Me("RET_IVA_HABILITA_RZO_SII") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("S")>  _
        Public Property RET_IVA_HABILITA_TODO() As String
            Get
                Return CType(Me("RET_IVA_HABILITA_TODO"),String)
            End Get
            Set
                Me("RET_IVA_HABILITA_TODO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N")>  _
        Public Property HABILITA_PROCESO_NORMAL() As String
            Get
                Return CType(Me("HABILITA_PROCESO_NORMAL"),String)
            End Get
            Set
                Me("HABILITA_PROCESO_NORMAL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property REINTENTOS_VALIDA_SII() As String
            Get
                Return CType(Me("REINTENTOS_VALIDA_SII"),String)
            End Get
            Set
                Me("REINTENTOS_VALIDA_SII") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.IntercambioRespuestasSII.My.MySettings
            Get
                Return Global.IntercambioRespuestasSII.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
