'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3615
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://161.131.232.99:8000/sap/bc/srt/rfc/sap/zservicios_fe_v2/300/zservicios_fe_"& _ 
            "v2/zservicios_fe_v2")>  _
        Public ReadOnly Property IntercambioRespuestasSII_WebReference_zservicios_fe_v2() As String
            Get
                Return CType(Me("IntercambioRespuestasSII_WebReference_zservicios_fe_v2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\Trabajos\IntercambioBCI_WS\Proceso\certificado_digital_firmante_efactura.p12")>  _
        Public Property CertPath() As String
            Get
                Return CType(Me("CertPath"),String)
            End Get
            Set
                Me("CertPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bcicacho")>  _
        Public Property CertPass() As String
            Get
                Return CType(Me("CertPass"),String)
            End Get
            Set
                Me("CertPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/CrSeed.jws")>  _
        Public Property RespuestasSII_cl_sii_semilla_CrSeedService() As String
            Get
                Return CType(Me("RespuestasSII_cl_sii_semilla_CrSeedService"),String)
            End Get
            Set
                Me("RespuestasSII_cl_sii_semilla_CrSeedService") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/GetTokenFromSeed.jws")>  _
        Public Property RespuestasSII_cl_sii_token_GetTokenFromSeedService() As String
            Get
                Return CType(Me("RespuestasSII_cl_sii_token_GetTokenFromSeedService"),String)
            End Get
            Set
                Me("RespuestasSII_cl_sii_token_GetTokenFromSeedService") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://palena.sii.cl/DTEWS/QueryEstDte.jws")>  _
        Public Property RespuestasSII_cl_sii_queryEstDte_QueryEstDteService() As String
            Get
                Return CType(Me("RespuestasSII_cl_sii_queryEstDte_QueryEstDteService"),String)
            End Get
            Set
                Me("RespuestasSII_cl_sii_queryEstDte_QueryEstDteService") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://192.168.0.50:3128/")>  _
        Public Property ProxyServer() As String
            Get
                Return CType(Me("ProxyServer"),String)
            End Get
            Set
                Me("ProxyServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("hfigueroa")>  _
        Public Property ProxyUser() As String
            Get
                Return CType(Me("ProxyUser"),String)
            End Get
            Set
                Me("ProxyUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("hfi-2012")>  _
        Public Property ProxyPass() As String
            Get
                Return CType(Me("ProxyPass"),String)
            End Get
            Set
                Me("ProxyPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\PROY_HFL2012\DTE_PRUEBA")>  _
        Public Property DtePath() As String
            Get
                Return CType(Me("DtePath"),String)
            End Get
            Set
                Me("DtePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("S")>  _
        Public Property RequiereProxy() As String
            Get
                Return CType(Me("RequiereProxy"),String)
            End Get
            Set
                Me("RequiereProxy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\PROY_HFL2012\DTE_PRUEBA\PROCESADOS")>  _
        Public Property DtePathProcOK() As String
            Get
                Return CType(Me("DtePathProcOK"),String)
            End Get
            Set
                Me("DtePathProcOK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property maximoIntentos() As String
            Get
                Return CType(Me("maximoIntentos"),String)
            End Get
            Set
                Me("maximoIntentos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\PROY_HFL2012\DTE_PRUEBA\RECHAZADOS")>  _
        Public Property DtePathProcNOK() As String
            Get
                Return CType(Me("DtePathProcNOK"),String)
            End Get
            Set
                Me("DtePathProcNOK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public Property VidaSemillaMil() As String
            Get
                Return CType(Me("VidaSemillaMil"),String)
            End Get
            Set
                Me("VidaSemillaMil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DTE Recibido")>  _
        Public Property DteEstOK() As String
            Get
                Return CType(Me("DteEstOK"),String)
            End Get
            Set
                Me("DteEstOK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\PROY_HFL2012\DTE_PRUEBA\LOG")>  _
        Public Property DteLogEnvio() As String
            Get
                Return CType(Me("DteLogEnvio"),String)
            End Get
            Set
                Me("DteLogEnvio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N")>  _
        Public Property WsBCI_Carga() As String
            Get
                Return CType(Me("WsBCI_Carga"),String)
            End Get
            Set
                Me("WsBCI_Carga") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.IntercambioRespuestasSII.My.MySettings
            Get
                Return Global.IntercambioRespuestasSII.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
